#message(warning "0")

#FILE(GLOB DLL_FILES "${OpenCV_DIR}/bin/${MSVC_BUILD_CONFIG_DIR}/*.dll")
#FILE(COPY ${DLL_FILES} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${MSVC_BUILD_CONFIG_DIR})

#message(warning "1")

FILE(GLOB DLL_FILES "${VTK_DIR}/bin/${MSVC_BUILD_CONFIG_DIR}/*.dll")
FILE(COPY ${DLL_FILES} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${MSVC_BUILD_CONFIG_DIR})

message(warning "${VTK_DIR}")

# #FILE(GLOB DLL_FILES "${CTK_DIR}/bin/${MSVC_BUILD_CONFIG_DIR}/*.dll")
# #FILE(COPY ${DLL_FILES} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${MSVC_BUILD_CONFIG_DIR})

# message(warning "3")

# FILE(GLOB DLL_FILES "${ITK_DIR}/bin/${MSVC_BUILD_CONFIG_DIR}/*.dll")
# FILE(COPY ${DLL_FILES} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${MSVC_BUILD_CONFIG_DIR})

# message(warning "4")

# FILE(GLOB DLL_FILES "${DCMTK_DIR}/bin/${MSVC_BUILD_CONFIG_DIR}/*.dll")
# FILE(COPY ${DLL_FILES} DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${MSVC_BUILD_CONFIG_DIR})

# message(warning "5")
# message(warning ${OpenCV_DIR})
# message(warning ${DLL_FILES})
# message(warning ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
# message(warning ${MSVC_BUILD_CONFIG_DIR})

# FOREACH(DLL_FILE ${DLL_FILES})
	# configure_file
	# # add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    # # COMMAND ${CMAKE_COMMAND} -E copy_if_different
        # # ${DLL_FILE}
        # # ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${MSVC_BUILD_CONFIG_DIR})	
# ENDFOREACH()